### ISSUE TITLE
Analysis on increasing ICU capacity

### ISSUE THREAD

**Issue by billlyzhaoyh** [AIforGoodSimulator/compartmental-model#10]
<img width="971" alt="Screenshot 2020-05-30 at 5 57 07 PM" src="https://user-images.githubusercontent.com/30638982/83363771-e70b0300-a393-11ea-9d0b-7c3a3884d3f1.png">
(Ignore the caption of the table which I haven't changed yet)

if we are setting the critical compartment to be people needing critical care but may or may not get it, then an increase in critical care capacity wouldn't increase the person-days needing the critical care but just reduce the number of deaths. Does it mean that people in critical care now are more likely to survive for another day thus attributing to the increase in critical person-days? But why we are seeing an increase in hospitalisation person days? Is the ICU number impacting that compartment in any way?

**Comment by billlyzhaoyh** [comment]
Are we setting the critical compartment to be people needing critical care but may or may not get it? If that is the case, this might be pointing towards a potential bug.

**Comment by nt409** [comment]
yeah that's the definition of that category... can change if you prefer? Otherwise it's just x get care if x<6 =capacity (capacity=6 for argument's sake but same point stands for a different parameter), or 6 get care and x-6 don't if x>6

**Comment by nt409** [comment]
The reason it increases hospitalisation days is that people that would have died recover and go back into hospital before full recovery or getting worse again
