### ISSUE TITLE
In moving sick people offsite (or isolating symptomatically infected people), number of cases go way below 0 in some cases

### ISSUE THREAD

**Issue by billlyzhaoyh** [AIforGoodSimulator/compartmental-model#12]
<img width="925" alt="Screenshot 2020-05-30 at 7 14 15 PM" src="https://user-images.githubusercontent.com/30638982/83363861-b8415c80-a394-11ea-877c-785e87be3b4b.png">

Here are three experiments I run for moving people offsite with two different rates (10 per day and 50 per day) from 0-80, 0-120 to 0-200 simulation days. The function to reproduce this experiment is at https://github.com/AIforGoodSimulator/compartmental-model/blob/master/Scripts/run_model_interventions.py

This is a plot over time for the symptomatically infected compartment. The plot directly plot the column of Infected (symptomatic) * N. The top graph has negative 500 in some runs - could this be a bug?

The code to reproduce is plot is 
```python
sns.lineplot(x="Time",y='Infected (symptomatic)',ci="sd",data=the_data_frame_to_plot)
```
From your comment, I understand now that the people who are sick will instantly flow into hospital or recovery and it will be great to add a delay there and maybe have a way to count how many people are currently isolated because that gives us an idea on how many people we need to care for. In this case, in any given day we can still count the number of symptomatically infected people across the whole camp including those people who are now living offsite so we don't misrepresent the situation in plotting very low symptomatic infection numbers.

**Comment by billlyzhaoyh** [comment]
also in this implementation, the sick people's hospitalisation needs and critical needs are not accounted for causing isolation to rank high in many of the categories (symptomatic infections, hospitalisation demand and critical care demand.

**Comment by nt409** [comment]
Can you send me any more details about the parameters you used to generate this? What exactly are you plotting on the y axis?

Not sure what the comment means... those who are sick are currently modelled to instantly flow into hospital or recovery. Ideally you might incorporate a delay but haven't yet included this - can do if desirable. Will have minor affect on hospital/critical stats (but all who would have gone into hospital do, albeit probably a few days early)

**Comment by nt409** [comment]
can't see anything that should go negative in current implementation so would be interested to know what you are plotting

**Comment by billlyzhaoyh** [comment]
right I see that makes sense I think ideally they will go into a quarantine state which they stay there for a few days and then progress to hospitalisation or recover? So in that way, we don't miss any daily demand on hospitalisation and also the number of people who are still symptomatically infected that day

**Comment by billlyzhaoyh** [comment]
A potential bug from sns.plot

**Comment by billlyzhaoyh** [comment]
bug fixed - changed confidence interval from 'sd' to 95%
