### ISSUE TITLE
A way to count how many symptomatically infected people are currently being isolated

### ISSUE THREAD

**Issue by billlyzhaoyh** [AIforGoodSimulator/compartmental-model#8]
Like moving high-risk residents offsite, can we have another bucket to track exactly how many people are being isolated at any given point? 

This can also help us understand the isolation capacity - once the residents recover or disease, the capacity opens up for more residents to come in. This might require a small overhaul on the current function setup.

**Comment by nt409** [comment]
added this in latest commit
